name: ci-golang-workflow
on: 
  pull_request: 
    branches:
        - development
        
jobs:
  test:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with: 
          go-version: 1.15
      - run: go test
      - run: go run math.go 

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        # Id serve pra pegar o resultado dessa action e usar em outro step
        id: docker_build
        uses: docker/build-push-action@v2
        with: 
          push: true
          tags: viqcinese/fullcycle-ci-go:latest